name: tube_search
description: youtube search
publish_to: 'none'
version: 1.1.3+5

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^1.1.0
  intl: ^0.20.2
  webview_flutter: ^4.4.1
  # ðŸ‘† ä»–ã®ä¾å­˜é–¢ä¿‚ã‚’ã“ã“ã«æ›¸ã
  logger: ^2.0.2
  shared_preferences: ^2.2.2
  provider: ^6.0.5
  google_mobile_ads: ^5.1.0
  flutter_keyboard_visibility: ^6.0.0
  connectivity_plus: ^6.0.3
  in_app_purchase: ^3.1.11
  url_launcher: ^6.3.0
  cached_network_image: ^3.4.0
  flutter_launcher_icons: ^0.13.1
  youtube_player_iframe: ^5.1.2
  flutter_custom_tabs: ^2.2.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

  # Android 13 (adaptive icon)
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/coming_soon.png
    - assets/images/splash_icon.png

  fonts:
    - family: NotoSansJP
      fonts:
        - asset: assets/fonts/NotoSansJP-Regular.ttf
        - asset: assets/fonts/NotoSansJP-Bold.ttf
          weight: 700

  generate: true

dev_dependencies:
  flutter_native_splash: ^2.4.4
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter

flutter_native_splash:
  color: "#0B3BDF"
  image: assets/images/splash_icon.png
  android: true
  ios: true

  android_12:
    color: "#0B3BDF"
    image: assets/images/splash_icon_android12_white.png
    icon_background_color: "#0B3BDF"